### ISSUE TITLE
So what needs to happen to use the loadoutcontroller?

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/TF-RED-Utils#3]
Details on where and how it needs to be placed inside the mission structure. Does it need to go into the folder with the loadouts or another folder entirely? I am getting ready with the revamp of Tanoa Takedown to start testing and want to make sure that the loadouts are working properly after they have been rebuilt.

**Comment by Jmaster9999** [comment]
This mod is separate from the loadout controller script. For those all you need to do is create a folder called 'Loadouts' and put the loadout-scripts in there. Or you could just extract contents of the loadout controller zip file into your missionfile and it will create a 'Loadouts' folder and put the scripts in it.
The folder NEEDS to be called 'Loadouts', otherwise the script won't be abe to find the loadouts.
